spring.application.name=profile-service

server.port=8086

# database configuration
spring.datasource.url=postgresql://ep-misty-scene-azuktg60-pooler.c-3.ap-southeast-1.aws.neon.tech/skillswap_profile_db?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_J1EOFArw0tim

#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect