spring.application.name=api-gateway

# API Gateway Port
server.port=8086


# ==========================================
# AUTH SERVICE - OAuth2 Start
# ==========================================

spring.cloud.gateway.server.webflux.routes[0].id=auth-oauth2
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/oauth2/**


# ==========================================
# AUTH SERVICE - User APIs
# ==========================================

spring.cloud.gateway.server.webflux.routes[1].id=auth-users
spring.cloud.gateway.server.webflux.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**


# ==========================================
# AUTH SERVICE - OAuth2 Authorization
# ==========================================

spring.cloud.gateway.server.webflux.routes[2].id=auth-oauth2-authorization
spring.cloud.gateway.server.webflux.routes[2].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/oauth2/**


# ==========================================
# AUTH SERVICE - OAuth2 Callback
# ==========================================

spring.cloud.gateway.server.webflux.routes[3].id=auth-oauth2-callback
spring.cloud.gateway.server.webflux.routes[3].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/login/oauth2/code/**


# ==========================================
# Eureka Client Configuration
# ==========================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Enable Eureka-based service discovery for Gateway
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# ==========================================
# DEBUG LOGGING - Eureka + LoadBalancer
# ==========================================

logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG

# ==========================================
# JWT configuration 
# ==========================================
jwt.secret=kdTqTYSIQ4ywNf7ZPnoliD2+De/IcQsQbje4V384dZ+/LUhSm/N/GXP1aQstH9nygph5zBwmV5ljPFsAT/TUcA==
jwt.expiration=86400000
